### ISSUE TITLE
CHANGE REQUEST: Suppress ePubs

### ISSUE THREAD

**Issue by ambersdai** [Connexions/cnx#127]
## Overview
Unfortunately, we do not currently support ePubs. We made a change a couple years ago to suppress ePubs on CNX. However, customer support noted that some of the books have ePubs available again.

This spreadsheet contains a list of the books that have ePubs on CNX.org (books with value "yes" in column B): https://docs.google.com/spreadsheets/d/1uP-ZsnGREwmd2QSiqsbmfbB3lP1b-k_y0WzJlvVvdHs

Minimally, we should suppress the files, because they are not valid and are causing complaints/questions for customer support. In this case, the ePub option should say "File not available".

Or, we may want to remove the "ePub" option entirely.
Severity: [ ] High [x] Medium [ ] Low
Frequency of Occurrence: [ ] High [x] Medium [ ] Low

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
No OpenStax books have ePubs available on cnx.org
There is a mechanism in place so that new OpenStax books will not get ePubs.

**Comment by openstaxalina** [comment]
superseded by: https://github.com/Connexions/cnx-archive/issues/594; closing
