### ISSUE TITLE
First-publish on production problem with atichinel

### ISSUE THREAD

**Issue by oscryan** [Connexions/cnx#19]
I’ve got a new-publish attempt https://legacy.cnx.org/Members/atichinel/Collection.2018-07-06.4635/collection_publish I can’t get through. The error says "You must specify at least one Author, Maintainer and Copyright Holder". When I try for the roles tab to see what’s up in there, I get 
Error Type
   KeyError
Error Value
   ‘Collection.2018-07-06.4635’
Request made at
   2018/08/29 21:53:24.098 GMT-5

# PR
https://github.com/Rhaptos/Products.RhaptosModuleEditor/pull/21

# Test Plan
For testing, you'll need to use a _new_ user (one without publish rights) to create a new ~module~ collection, then _remove all authors_. Ignore the big orange warning. Go to "submit for publishing review" via the publishing tab. This will work (though arguably it shouldn't)

As an admin user, go to the now `pending` content, try to publish. Should say "missing authors" and take you to the roles tab, with no traceback or error. ~You can then alter it~, or go to publish tab to 'withdraw' the content.

You can append `/collection_publish` to the end of the URL, after the part that looks like `collection.2018-09-13.3234420844`, as a global maintainer to test the admin side.

**Comment by reedstrm** [comment]
OK ,this one took some digging. Seems Alyssa took herself off of both author and licensor, and tried to publish, despite the big orange boxes saying you can't do that. It _did_ allow her to submit (for pending) however. So when Ryan tried to publish, the system dropped out at "missing roles", and attempted to take you to the "Roles" tab, to fix things. That tab, however, isn't set up for "pending" content, so hit an error. It _does_ work to "withdraw" the content, setting the state back to "created". The roles tab then works.

**Comment by openstaxalina** [comment]
Asked CS to follow up with the user and explain roles and next steps.

**Comment by reedstrm** [comment]
Since I did all the debugging, I just created a PR for RhaptosModuleEditor, to avoid the traceback :-) This will allow global maintainers to modify pending content, which will withdraw it from pending, allowing the original author to see it and make further corrections.

**Comment by reedstrm** [comment]
https://github.com/Rhaptos/Products.RhaptosModuleEditor/pull/21

**Comment by kerwinso** [comment]
@Dantemss Please provide a test plan for this, thanks.

**Comment by reedstrm** [comment]
For testing, you'll need to use a _new_ users (one without publish rights) to create a new module, then _remove all authors_. Go to "submit for publishing review" via the publishing tab.

As an admin user, go to the now `pending` content, try to publish. Should say "missing authors" and take you to the roles tab, with no traceback or error. You can then alter it, or go to publish tab to 'withdaw' the content.

**Comment by kerwinso** [comment]
Replicated this error on staging, need to test after repo has been packaged.
![image](https://user-images.githubusercontent.com/11298165/45500903-692d4100-b745-11e8-9169-4f449ea84d06.png)

**Comment by kerwinso** [comment]
Verified working on https://qa.cnx.org/contents/WP_phCyX, need to verify on staging.

**Comment by kerwinso** [comment]
@reedstrm This is failing on staging. When I log in to the admin side to `/collection_publish`, it kicks me back to https://legacy-staging.cnx.org/Members/easymix/Collection.2018-09-17.3514/content_roles (which is correct). However, after I assign an author and copyright holder and attempt to Submit Changes, I get the following KeyError:

![image](https://user-images.githubusercontent.com/11298165/45646523-3490f080-ba89-11e8-9f78-cc82492def8a.png)

Perhaps this is due to a partial deployment on the staging front end servers.

**Comment by kerwinso** [comment]
Trying to alter the roles as an admin is throwing an error on legacy-staging, even though it works on legacy-qa. Guh?! 

So, @reedstrm & I have decided to "adjust" the Acceptance Criteria to just be that the admin user can withdraw the content, then contact the author to update their roles and submit again for publication. By this new criteria, this issue passes. ;-)

FYI @openstaxalina @lwtchu @oscryan
