### ISSUE TITLE
SEO: Adjust Canonical Links for Pages Shared Across Books

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx#191]
## Overview
See [this story]( https://docs.google.com/document/d/1tePCvQVjK2Zkd8NTZx1UQEhsq85Tl614becyMouzIVo/edit#heading=h.1ia6zq5njsty ) for background.
The first tab of [this spreadsheet](https://docs.google.com/spreadsheets/d/1Hj5vm2AbEiLgxgcbNRi550InzFTLvBOv16-Fw6P-c5E/edit#gid=2066350488) details the desired canonical link mapping for for all OpenStax books, with books that share modules highlighted at the top of the list.

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by omehes** [comment]
Discussed test plan with Ed. 
Steps to follow:
1. find pages which are shared across different books (e.g. biology and economics)
2. find the canonical link in each page
3. compare those with the canonical link in the master (source) book

Books only by OpenStax authors 

test results:
macroecon: <meta property="og:url" content="https://staging.cnx.org/contents/MwdgVOwd@4.1:urcPvnrk@5">

<link rel="canonical" href="https://staging.cnx.org/contents/ca344e2d-6731-43cd-b851-a7b3aa0b37aa:bab70fbe-7ae4-431b-8a64-feb58cff7f23">

microecon:
<meta property="og:url" content="https://staging.cnx.org/contents/yjROLWcx@5.6:urcPvnrk@5">

link rel="canonical" href="https://staging.cnx.org/contents/ca344e2d-6731-43cd-b851-a7b3aa0b37aa:bab70fbe-7ae4-431b-8a64-feb58cff7f23">
