### ISSUE TITLE
Re-doing Testing

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx#211]
`# (Recurring) Webview, legacy, and batch regression tests for 201X.XX.XX release`
These tests cannot start until we get RC code onto staging.

CNX regression test run milestone link: INSERT TESTRAIL LINK

- [ ] Make sure Sourav can publish on staging 
- [ ] Prepare and send out test runs
- [ ] Monitor/follow up on offshore testers 
- [ ] Non-offshore regression tests
- [ ] Batch regression tests

**Smoke Testing** process for redeployment on staging.cnx.org:

1. smoke test of webview:
- version numbers
- all books are present
- header buttons
- advanced search
- footer buttons
- contents button, back, next
- chapters, pages
- pdf and zip downloads
- More information

2. smoke test of legacy editor:
- publish book with changes in summary/keywords
- publish with recipe/ccap

version:
{"date": "2018-12-18 08:50:04 CST",
 "webview": "9afc493b8f9c2fee608555a680fccda15d57d569 (v0.43.0)",
 "cnx-archive": "4.7.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "xiao.xiao v0.68.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.33.2"
}

3. smoke testing of batch:
- Complete Test Cases group in [test rails](https://openstax.testrail.com/index.php?/suites/view/70&group_by=cases:section_id&group_id=16202&group_order=asc). This involves only 3 major tests.

**Comment by omehes** [comment]
Testing progress on redeployed staging.cnx.org:

1. smoke test of staging.cnx.org:
- version numbers
- all books are present
- header buttons
- advanced search
- footer buttons
- contents button, back, next
- chapters, pages
- pdf and zip downloads
- More information
2. smoke test of legacy:
- publish book with changes in summary/keywords
- publish with recipe/ccap

version:
{"date": "2018-12-18 08:50:04 CST",
 "webview": "9afc493b8f9c2fee608555a680fccda15d57d569 (v0.43.0)",
 "cnx-archive": "4.7.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "xiao.xiao v0.68.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.33.2"
}

**Comment by Bkblodget** [comment]
Batch smoke testing for 12.18 completed & passed.

**Comment by brittweinstein** [comment]
All testing complete.
