### ISSUE TITLE
For each independent page (all versions) of OpenStax content, add a canonical tag that points to the corresponding page-in-book of the most updated version within the master book on CNX.org

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx#28]
## Overview/Purpose
This will help Google spiders know what content to crawl among our duplicate content.
## Design/Notes
Technical implementation is in webview to update the html header, much like the title tag is updated, as each new page is viewed.
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/webview #1959](https://github.com/Connexions/webview/issues/1959) via [**ZenHub**](https://www.zenhub.com/)
