### ISSUE TITLE
Explain templates on parameters page

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx#31]
## Overview
Now that we have a significant amount of CCAP and "w/ recipe" templates, Customer Support is beginning to field questions about what these mean.  We need to add some copy to the parameters tab/page in the Legacy editor to explain this.  [Alina to create copy.]
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by Bkblodget** [comment]
This was fixed with https://app.zenhub.com/workspaces/cnx-team-5af1f4cc12da5e6d74331b60/issues/connexions/products.rhaptoscollection/16
