### ISSUE TITLE
Fix or Remove "Preview" option for users editing CNX content

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx#37]
#Scenario
When a user is creating content in legacy CNX they are given the option to preview their resource to see what it will look like before they publish it.  This routinely breaks, yielding a 404 error.

According to the content managers:
"...the preview button isn’t reliable"
"... it isn’t a guarantee of how it’ll show up in CNX or the PDF"
"we don’t use it cause it’s essentially useless"

The preview option needs to be fixed to enable its use or needs to hidden/removed so that users don't struggle with a broken feature.

#Steps to Reproduce

* **Product**: [ ] Tutor   [ ] Concept Coach [ ] OS Web [ ] Content Production Toolkit [X] CNX

* **How many times were you able to reproduce the issue?** 
95% of the time?

* **Images or Screenshots Included:** [ ] Yes  [X] No  (_attach below_)

#Environment:

* **Instance**: [X] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [X] Mac OSX  [X] Windows  [ ] iOS  [ ] Android
* **Browser**: [X] Chrome  [X] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

#Impact

* **Severity**: [ ] High [X] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [X] Medium  [ ] Low

**Comment by openstaxalina** [comment]
Moved here: https://github.com/Rhaptos/Products.RhaptosModuleEditor/issues/23

**Comment by edwoodward** [comment]
@brittweinstein Should this be closed? I updated the new issue in RhaptosModuleEditor.

**Comment by brittweinstein** [comment]
@edwoodward yes, I will close this issue.

**Comment by openstaxalina** [comment]
Changes just discussed with @edwoodward and @reedstrm.  cc @omehes - we will try to get all of these changes into the next rev on staging.

![RemovingPreview.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd9230155135af60-21b5-49bd-b209-b5173cb07576)
