### ISSUE TITLE
Provide a collection.xml document for all collection versions

### ISSUE THREAD

**Issue by ambersdai** [Connexions/cnx#95]
## Overview
We'd like to have a collxml document for all Collections and their versions. This will enable us to fetch the document from within Press without depending on the legacy software.

We would like to do a simple SQL select to obtain the `collection.xml`. This is the case for [GET /api/collections/{id}/{version}](https://trello.com/c/4vTfGeDk/).

Ross has requested to do this implementation. He'd like to implement the solution in the database. I (M. Mulich) am on board with that that implementation idea. Ross should be contacted to provide more technical detail about the implementation details for working on this.

This is related to Batch and Legacy2Press.
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria

- All versions of a Collection (specifically minor versions) have a collection.xml document in the database. This can be verified by looking at the resources associated with the content at `<archive>/contents/{uuid}[@{version}].json`
- Metadata for the collection is accurately contained in the persisted collection.xml document. This can be verified by downloading the resource via `<archive>/resources/{sha1}`. You can get the `sha1` value from the aforementioned resources listing in the general content route.

**Comment by reedstrm** [comment]
closing in favor of Connexions/cnx-db#148
